module.exports = [
  { file: 'localdb.js',
    module: 'node-red',
    name: 'localdb',
    version: '0.11.2-git' },
  { file: 'sentiment.js',
    module: 'node-red',
    name: 'sentiment',
    version: '0.11.2-git' },
  { file: 'inject.js',
    module: 'node-red',
    name: 'inject',
    version: '0.11.2-git' },
  { file: 'geolocate.js',
    module: 'node-red',
    name: 'geolocate',
    version: '0.11.2-git' },
  // { file: 'catch.js',
  //   module: 'node-red',
  //   name: 'catch',
  //   version: '0.11.2-git' },
  // { file: 'status.js',
  //   module: 'node-red',
  //   name: 'status',
  //   version: '0.11.2-git' },
  { file: 'debug.js',
    module: 'node-red',
    name: 'debug',
    version: '0.11.2-git' },
  { file: 'notify.js',
    module: 'node-red',
    name: 'notify',
    version: '0.11.2-git' },
  { file: 'espeak.js',
    module: 'node-red',
    name: 'espeak',
    version: '0.11.2-git' },
  // { file: 'exec.js',
  //   module: 'node-red',
  //   name: 'exec',
  //   version: '0.11.2-git' },
  { file: 'function.js',
    module: 'node-red',
    name: 'function',
    version: '0.11.2-git' },
  { file: 'gpio.js',
    module: 'node-red',
    name: 'gpio',
    version: '0.11.2-git' },
  { file: 'meshblu.js',
    module: 'node-red',
    name: 'meshblu',
    version: '0.11.2-git' },
  { file: 'template.js',
    module: 'node-red',
    name: 'template',
    version: '0.11.2-git' },
  // { file: 'delay.js',
  //   module: 'node-red',
  //   name: 'delay',
  //   version: '0.11.2-git' },
  // { file: 'trigger.js',
  //   module: 'node-red',
  //   name: 'trigger',
  //   version: '0.11.2-git' },
  { file: 'comment.js',
    module: 'node-red',
    name: 'comment',
    version: '0.11.2-git' },
  // { file: 'unknown.js',
  //   module: 'node-red',
  //   name: 'unknown',
  //   version: '0.11.2-git' },
  // { file: 'rpi-gpio.js',
  //   module: 'node-red',
  //   name: 'rpi-gpio',
  //   version: '0.11.2-git' },
  // { file: 'mqtt.js',
  //   module: 'node-red',
  //   name: 'mqtt',
  //   version: '0.11.2-git' },
  { file: 'httpin.js',
    module: 'node-red',
    name: 'httpin',
    version: '0.11.2-git' },
  { file: 'camera.js',
    module: 'node-red',
    name: 'camera',
    version: '0.11.2-git' },
  // { file: 'websocket.js',
  //   module: 'node-red',
  //   name: 'websocket',
  //   version: '0.11.2-git' },
  // { file: 'watch.js',
  //   module: 'node-red',
  //   name: 'watch',
  //   version: '0.11.2-git' },
  // { file: 'tcpin.js',
  //   module: 'node-red',
  //   name: 'tcpin',
  //   version: '0.11.2-git' },
  // { file: 'udp.js',
  //   module: 'node-red',
  //   name: 'udp',
  //   version: '0.11.2-git' },
  { file: 'switch.js',
    module: 'node-red',
    name: 'switch',
    version: '0.11.2-git' },
  { file: 'change.js',
    module: 'node-red',
    name: 'change',
    version: '0.11.2-git' },
  { file: 'range.js',
    module: 'node-red',
    name: 'range',
    version: '0.11.2-git' },
  // { file: 'CSV.js',
  //   module: 'node-red',
  //   name: 'CSV',
  //   version: '0.11.2-git' },
  // { file: 'HTML.js',
  //   module: 'node-red',
  //   name: 'HTML',
  //   version: '0.11.2-git' },
  { file: 'JSON.js',
    module: 'node-red',
    name: 'JSON',
    version: '0.11.2-git' },
  // { file: 'XML.js',
  //   module: 'node-red',
  //   name: 'XML',
  //   version: '0.11.2-git' },
  // { file: 'tail.js',
  //   module: 'node-red',
  //   name: 'tail',
  //   version: '0.11.2-git' },
  // { file: 'file.js',
  //   module: 'node-red',
  //   name: 'file',
  //   version: '0.11.2-git' }
  { file: 'socketio.js',
    module: 'node-red',
    name: 'socketio',
    version: '0.11.2-git' },
  { file: 'eventsource.js',
    module: 'node-red',
    name: 'eventsource',
    version: '0.11.2-git' },
  { file: 'peer2peer.js',
    module: 'node-red',
    name: 'peer2peer',
    version: '0.11.2-git' }
];

