const nodeDefs = [
  require('./analysis/sentiment'),
  //require('./core/catch'),
  //require('./core/status'),
  require('./core/debug'),
  //require('./core/exec'),
  //require('./core/delay'),
  //require('./core/trigger'),
  //require('./core/unknown'),
  //require('./core/mqtt'),
  require('./core/template'),
  require('./core/function'),
  require('./core/espeak'),
  require('./core/notify'),
  require('./core/inject'),
  require('./core/comment'),
  require('./io/httpin'),
  //require('./io/websocket'),
  //require('./io/watch'),
  //require('./io/tcpin'),
  //require('./io/udp'),
  require('./io/camera'),
  require('./io/meshblu'),
  require('./io/gpio'),
  require('./io/peer2peer'),
  require('./io/socketio'),
  require('./io/geolocate'),
  require('./logic/switch'),
  require('./logic/range'),
  require('./logic/change'),
  //require('./parsers/xml'),
  //require('./parsers/html'),
  //require('./parsers/csv'),
  require('./parsers/json'),
  //require('./storage/file'),
  //require('./storage/tail'),
  require('./storage/localdb')
];

module.exports = function(RED){
  nodeDefs.forEach(function(n){
    n(RED);
  });
}
